apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: harrhelm
  namespace: uat
spec:
  components:
  - name: harrhelm-harrhelm-k8s
    properties:
      chart: hello-world
      installTimeout: 10m
      interval: 30s
      pullInterval: 5m
      repoType: helm
      retries: 3
      url: https://helm.github.io/examples
      version: 0.1.0
    type: helm
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
