apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 7d89391a399b7cdb11f13f625248e9bee17cb788
    application.deploy.reform/deploymentNo: harr1-DP8
    application.deploy.reform/name: harr1
    application.deploy.reform/revision: 2023.03.8
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: harr1
  namespace: uat
spec:
  components:
  - name: harr1-harr1-k8s
    properties:
      chart: hello-world
      installTimeout: 10m
      interval: 30s
      pullInterval: 5m
      repoType: helm
      retries: 3
      url: https://helm.github.io/examples
      version: 0.1.0
    type: helm
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
