apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: ware2131
  namespace: uat
spec:
  components:
  - name: ware2131-we-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: ngnix
      imagePullPolicy: IfNotPresent
      memory: 200Mi
      ports:
      - expose: true
        name: http
        port: 80
        protocol: TCP
    traits:
    - properties:
        class: nginx
        classInSpec: false
        http:
          /: 80
      type: gateway
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
